### ISSUE TITLE
Continuing development of this Project

### ISSUE THREAD

**Issue by juicycleff** [zino-app/graphql-flutter#168] opened 2019-02-11 13:56 UTC
**Current State of this Project**
So if you are aware of what is happening right now, this repo is not maintained much anymore. I have tried reaching @HofmannZ here but got no reply, hope he reaches back soon. I am however continuing development of this project in my repo which I will share here later today. If @HofmannZ comes back to maintaining the repo, I will, of course, be happy to merge it back into this repo. Thank you.

Here is the new repo https://github.com/juicycleff/flutter-graphql

**Comment by olup** [comment] 2019-02-11 14:08
Cool ! So I'll create my MR's on your repo directly.

**Comment by juicycleff** [comment] 2019-02-11 19:45
@olup yes sir. I cleaned up and here is the link https://github.com/juicycleff/graphql-flutter/tree/master

**Comment by juicycleff** [comment] 2019-02-11 19:46
I also published to pub dart 
https://pub.dartlang.org/packages/flutter_graphql

**Comment by juicycleff** [comment] 2019-02-11 19:50
Will be removing the entire branches saving master. I will draw some plans and go from there. But you can send your PRs

**Comment by HofmannZ** [comment] 2019-02-11 20:51
Hello everyone,

As you all know we've not been able to maintain this project. This was due to some rearrangements of our resources in private projects. Simply put, we did not have enough time to also maintain this project. As a result, both the issue and PRs are piling up.

We really believe in the Flutter, especially in combination with GraphQL and are therefore currently working on a way to keep this project rolling.

We're planning to have a short planning session (SCRUM-ish) this weekend followed by a coding session that same weekend. Since we look at this as a community project, we'd like to collect as much input as possible. Therefore we're creating a survey to get some general insight into the community. We also like you to join us this weekend with either writing some code or doing some code reviews.

We are excited to pick up this project again, and we hope that you are too.

Zino

> I'll update this post with the link to the survey tomorrow.

**Comment by juicycleff** [comment] 2019-02-11 21:29
@HofmannZ Nice for you to show back. I will halt whatever I am doing until this weekend. Can't wait to see the outcome 😄

**Comment by HofmannZ** [comment] 2019-02-13 19:11
@juicycleff not sure if you get an update when I edit a comment so here’s the link to the survey: https://goo.gl/forms/WZ5JlNWASxd1ojfG3

**Comment by wwwdata** [comment] 2019-02-13 22:51
Hi, great that you want to make a survey. But I guess you have to check the permissions. I get an error that says only users in the owners organization can see the form.

**Comment by olup** [comment] 2019-02-14 00:01
Yeah, please check settings and open up the form for every one.

**Comment by HofmannZ** [comment] 2019-02-14 06:56
@wwwdata @olup Oh, did not know it locks it down by default. Updated the settings, and it should work now!

**Comment by wwwdata** [comment] 2019-02-14 07:20
I could not make it past page 2 in the survey.. Clicking the next button does not do anything for me. Was using Chrome browser. I don't know if that is a problem that you can fix or some google forms problem 🤷‍♂️

**Comment by HofmannZ** [comment] 2019-02-14 09:16
@wwwdata Could reproduce, looks like it's solved now.

**Comment by robert-stevens** [comment] 2019-02-15 13:53
@HofmannZ @juicycleff 

This is good news. I think most of us would like to know what is left to get a stable/beta 1.0.0 version and how long that would take between those involved.

If we could have an indication of that by after this weekend it will be great, as that will definitely help other devs in deciding to use this package or not.

**Comment by juicycleff** [comment] 2019-02-16 12:24
Hi @HofmannZ, I didn't get a notification. I filled in the survey. What next?

**Comment by juicycleff** [comment] 2019-02-16 12:28
@robert-stevens from my test, time should be spent on the cache and also pluggable persistent storage. Following the apollo-link-state pattern, so it is extensible. I am waiting for @HofmannZ plans. I halted my project for this so, I might jump back to dev if it delays too long

**Comment by HofmannZ** [comment] 2019-02-16 18:43
Hello everyone,

Thanks for all the great feedback on the survey! We think the answers added some great insights into the project. And since it did not include any sensitive data, we've enabled you to view the results.

We really want to push this project to a stable version and are therefore dedicating more time to maintaining it. We also think it's good to let you guys decide which features will end up in the client. Therefore we're requiring 3 peer-review per pull request, encouraging you more developers to get involved into the pull requests. 

Today we also made some first steps by releasing our first beta. You can get it in your project today by requiring `graphql_flutter: ^1.0.0-beta`.

We hope we can continue building something great!

Zino

**Comment by sjmcdowall** [comment] 2019-02-16 20:04
@HofmannZ -- With over 15 years experience with Opensource Software, may I make a humble suggestion and to OPEN this project, since it's so critical to many people, as a real open source with more contributors, people who can pub etc.  I would certainly nominate @juicycleff to be a core contributor etc. and maybe 1 or 2 others .  That way there isn't a "single" source (1 company) change of being abandoned with no ability for anyone to take over and keep it moving.

**Comment by HofmannZ** [comment] 2019-02-16 20:34
@sjmcdowall Definitely a great suggestion! @juicycleff are you open to joining as a core contributor?

**Comment by dbanck** [comment] 2019-02-17 12:07
Happy to hear that you guys are back and the development of this great library continues! We've been using the `next` branch with good success in an internal project so far. ❤️ 

I like @juicycleff suggestion of following the apollo-link pattern, but I think this somewhat implies a more modular approach to GraphQL in Dart. What do you think of decoupling the internal GraphQL part from Flutter? There are no real dependencies on Flutter when using GraphQL with Dart. Furthermore there could be a smaller library on top of that providing the Flutter widgets (think [react-apollo](https://github.com/apollographql/react-apollo)). 

This would allow anyone wanting to work with GraphQL and Dart to use the "base" library which is then accompanied by Flutter widgets library for anyone who is using Flutter. Furthermore we could test all the core business logic without having to depend on Flutter.

What do you think? This isn't something which should be done for the release of a stable `1.0.0` version, but might be an interesting thought for the future.

**Comment by HofmannZ** [comment] 2019-02-17 12:28
@dbanck When we build the first version of the client, we took a load of inspiration from Apollo. This was done assuming that most people would already be familiar with the Apollo project and could, therefore, find there way around more easily.

The survey showed that the assumption was quite accurate, 89% of the respondents used Apollo before using this client. We, therefore, think it's a good decision to also use the modular link approach. We already made the first link available `AuthLink`, which does by popular request, provide a single point to provide Authorization.

Decoupling Dart from Flutter is definitely something we would like to do in the future. Though we think the current focus should lay on setting up a solid open source community. Hence we created a poll where we everyone can vote on who should become the new core contributors for this project.

https://goo.gl/forms/19KNF9IMuBKGngrz2

Zino

**Comment by dbanck** [comment] 2019-02-17 12:43
There is a lot to learn from Apollo and basing this library on their architecture is definitely a good decision.

@HofmannZ You might have to check the permissions of the new survey, I'm getting the "This form can only be viewed by users in the owner's organization." error.

**Comment by HofmannZ** [comment] 2019-02-17 12:50
@dbanck Should be fixed now

**Comment by robert-stevens** [comment] 2019-02-19 10:06
@HofmannZ 

Thanks for the updates, I am going to check out the beta, any news/progress on optimistic results?

**Comment by juicycleff** [comment] 2019-02-19 16:50
> @sjmcdowall Definitely a great suggestion! @juicycleff are you open to joining as a core contributor?

Yes, I am definitely

**Comment by sjmcdowall** [comment] 2019-02-19 16:57
FWIW -- I'd be ok as a backup publisher / merger / reviewer etc. too if desired...

**Comment by HofmannZ** [comment] 2019-02-24 15:24
Okay, the poll has three clear preferences: @cal-pratt, @camuthig and @juicycleff.

Are you guys cool with helping maintain the project? If so, shoot me an email to zino@zinoapp.com and I'll add you to the project.

**Comment by cal-pratt** [comment] 2019-02-24 16:23
@HofmannZ Hey, everyone. Thanks a lot for including me in this vote, but I'm going to take my hat out of the ring. I've become fairly busy with other priorities and havent been able to continue my Flutter experiments as I'd like. I would be happy to help in code reviews or general discussion from time to time, but I dont think I have enough cycles in the day to act as a useful core contributor. Thanks again!

**Comment by camuthig** [comment] 2019-02-25 08:54
I appreciate the vote of confidence, but I don't believe I can help out. I haven't worked with Dart since nearly my last commit to this project and already have other projects in the works that are taking up my bandwidth.

**Comment by HofmannZ** [comment] 2019-02-25 09:45
@cal-pratt @camuthig I understand that you do not have time to help to maintain the project. I just dropped in all the contributors into the hat ;)

@degroote22 @micimize You both received a load of votes as well. Do you guys have the time and willingness to help to maintain the project with us?

If so, shoot me an email to [zino@zinoapp.com](mailto:zino@zinoapp.com) and I'll add you to the project.

**Comment by micimize** [comment] 2019-02-25 17:53
@HofmannZ I'd be happy to! I have been fairly swamped recently, but that should be letting up soon and then I'll have time to focus on flutter stuff a lot more.

@robert-stevens (also maybe @juicycleff) It's not robust/tested enough to PR yet, but the most recent work I did on my fork was on [adding optimism](https://github.com/micimize/graphql-flutter/commits/lazy_dereference)

**Comment by juicycleff** [comment] 2019-02-27 11:41
@micimize that's awesome. Would you like to finish it off, or someone else picks it up?

**Comment by micimize** [comment] 2019-02-28 22:23
@juicycleff if someone else wants to pick it up that's fine with me, not sure what condition it's in though - might be out of sync, definitely doesn't have enough tests. I'll hopefully have time to get back to it sometime soon

**Comment by juicycleff** [comment] 2019-03-02 21:33
@micimize that's fine. I would like to take a look, but I want to focus on persistent caching for now. However @HofmannZ I didn't get the invitation, did you send it?

**Comment by HofmannZ** [comment] 2019-03-03 17:35
Hi @juicycleff, the invitation should've been in your inbox on the 26th. I just resend you the invitation link. Can you let me know if you've received it this time?

**Comment by juicycleff** [comment] 2019-03-04 22:51
Yeah I did

**Comment by juicycleff** [comment] 2019-03-04 22:51
Thank you :)

**Comment by leoafarias** [comment] 2019-03-06 15:44
@juicycleff @HofmannZ There is a lot of discussions internally in our company on which package, and version to use. I assume that after this last few messages, we should stick on using this version of the package which @juicycleff will be merging his improvements and making core contributions to does that sound right?

**Comment by micimize** [comment] 2019-03-07 23:59
@leoafarias Yes, unless you want to make use of @juicycleff's changes right this second, that's correct.

**Comment by juicycleff** [comment] 2019-03-15 08:11
Correct

**Comment by leoafarias** [comment] 2019-03-19 14:13
@juicycleff @HofmannZ sorry, there seems to be now another version of flutter-graphql. 
https://github.com/snowballdigital/flutter-graphql

An updated readme on this repository pointing to this new version would be great

**Comment by jcraven-worksight** [comment] 2019-03-19 22:15
@leoafarias that is @juicycleff's fork of this repository, although I'm not sure if it's intended to replace this one.

**Comment by ChristBKK** [comment] 2019-03-24 08:52
quite confused right now. Which of the repos are maintained now? This? https://github.com/juicycleff/flutter-graphql  or https://github.com/snowballdigital/flutter-graphql this?  OR  https://github.com/zino-app/graphql-flutter ?

**Comment by eusdima** [comment] 2019-03-24 08:57
@ChristBKK those two are just unofficial forks and not intended to replace the current one.

**Comment by ChristBKK** [comment] 2019-03-24 17:56
@eusdima  yeah but this one seems to be lost? isn't @juicycleff  maintaining it well? Why can't he takeover or commit to this one here then?

**Comment by eusdima** [comment] 2019-03-24 18:02
@ChristBKK The plan was to pick people that are willing to continue developing this repo and @juicycleff was one of them. Since I didn't see him having any activity here, but he maintains mostly his forks, I removed him from graphql-fluter.

**Comment by eusdima** [comment] 2019-03-24 18:44
If you want to help the project you can respond to #196

**Closed by eusdima** 2019-03-24 18:44 UTC
Labels: next, question

**Comment by micimize** [comment] 2019-03-24 18:56
The [snowballdigital](https://github.com/snowballdigital/flutter-graphql) fork is also @juicycleff's fork. He'll probably [consolidate them](https://github.com/snowballdigital/flutter-graphql/issues/4) soon, and has [expressed interest in making PR's and consolidating efforts](https://github.com/zino-app/graphql-flutter/pull/180#issuecomment-472190494), but has been quite busy (like all of us).

I'd recommend following #197 for tracking the progress we make on consolidation.

**Comment by juicycleff** [comment] 2019-03-25 07:34
Hi sorry for all the confusion. My fork at https://github.com/juicycleff/flutter-graphql  was little messed up because I had stripped of a lot of this repo branches and tags and did a lot of change to simplify the process of contributing and that was before Hoffman responded. However, I found out the pace of reviewing PRs here was quite slow and is affecting my project and I also have people in my company interested in Flutter and I decided to have work on this at my own pace and have my colleagues contribute. As moving forward. The two forks are still quite different and I am still considering an approach. I recently relocated to Norway so I was quite unavailable. I just need to get my project fully functional hence I need a replica of react-apollo asap for flutter, which means I will hold on to my repo for a bit. There are great possibilities to merge in the future, but for now, I just need this on RAD. I hope this clears out any confusion.

**Comment by eusdima** [comment] 2019-03-25 09:48
@juicycleff I am sorry I overreacted about what I said. But I want this project to move forward faster. The goal of GraphQL-flutter was always to become an apollo-client. Would be great if you could join the discord channel referenced in #196 where I would like to hear more about the great work that you are doing in your library and possibly discuss the roadmap.

**Comment by juicycleff** [comment] 2019-03-26 08:16
Its fine @eusdima. Sorry I saw the discussion last night, but I had to sleep as it was a bit late and I'm getting used to weather
