### ISSUE TITLE
How to decode UTF-8 chars in response?

### ISSUE THREAD

**Issue by endigo** [zino-app/graphql-flutter#95] opened 2018-09-11 08:34 UTC
We have a Cyrillic (Mongolian) texts returned from GraphQL API.

But Cyrillic texts are obscured. Something like this.
![screen shot 2018-09-11 at 4 30 37 pm](https://user-images.githubusercontent.com/1501644/45348104-4cc3c400-b5e0-11e8-9015-60516c43f6c5.png)

We write a custom UTF-8 converter.

```dart
static String utf8convert(String text) {
    List<int> bytes = text.toString().codeUnits;
    return utf8.decode(bytes);
}
```

And the result is here
![screen shot 2018-09-11 at 4 35 19 pm](https://user-images.githubusercontent.com/1501644/45348247-b9d75980-b5e0-11e8-8a1c-9f5413e1a7cc.png)

**Comment by HofmannZ** [comment] 2018-09-11 12:41
Might be related #94

**Comment by HofmannZ** [comment] 2018-09-11 12:42
@endigo which version of the client are you using?

**Comment by endigo** [comment] 2018-09-11 21:47
@HofmannZ I'm using 1.0.0-alpha6.

**Comment by HofmannZ** [comment] 2018-09-11 21:58
@endigo Which `Content-Type` is your endpoint returning? Should be: `Content-Type: 'application/json; charset=utf-8'`, so that the http client can decode utf8.

**Comment by endigo** [comment] 2018-09-11 22:27
in the server's response header?

**Comment by HofmannZ** [comment] 2018-09-12 08:51
@endigo Yes, in the server's response header.

**Comment by HofmannZ** [comment] 2018-09-21 16:46
Fixed with 1.0.0-alpha.8

**Closed by HofmannZ** 2018-09-21 16:46 UTC
Labels: question

**Comment by kieusonlam** [comment] 2018-09-26 07:15
Hi guys,

Does the issue is fixed or just me still get this problem :( 

My package version: 1.0.0-alpha.9

![image](https://user-images.githubusercontent.com/13093313/46063129-18cad000-c196-11e8-9e90-cdcb227a583d.png)

**Comment by AngeloContrera5** [comment] 2021-11-15 19:46
@endigo thank u so much :3 <3
