### ISSUE TITLE
Generated Code / Class for GraphQL query/mutation

### ISSUE THREAD

**Issue by truongsinh** [zino-app/graphql-flutter#159] opened 2019-01-18 03:07 UTC
**Is your feature request related to a problem? Please describe.**
Query/Mutation is now created from schema string at runtime https://github.com/zino-app/graphql-flutter#queries , thus more error-prone than compile time.

**Describe the solution you'd like**
Using code generated (ref https://medium.com/flutter-community/part-2-code-generation-in-dart-annotations-source-gen-and-build-runner-bbceee28697b) from `*.graphql` schema, similar to some ORM, or https://github.com/apollographql/apollo-android#generate-code-using-apollo

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by degroote22** [comment] 2019-02-22 14:24
This is a duplicate of #26 
I have a generator written in typescript which need node to run.
[This is what code written with it looks like](https://github.com/zino-app/graphql-flutter/compare/master...degroote22:master)

I suggested that we support this generator with this project but people did not like the idea of using node with dart.
I can open source my generator if you want but bear in my that is heavily opinionated on some points and I don't plan to change it, but feel free yourselves to fork it.

I'm taking a few days off but if there is interest in it I'll publish the source code and the package on NPM next week.

**Comment by truongsinh** [comment] 2019-02-23 01:54
I understand why we don't want to mix Dart VM and Node/V8 VM. It's great idea to open source your generator. I'll also read #26 to see how we can come to a solution without Node/V8 VM involved

**Comment by micimize** [comment] 2019-03-26 16:47
Consolidating this into #26 and continuing discussion there

**Closed by micimize** 2019-03-26 16:47 UTC
