### ISSUE TITLE
[v4] Error on subscribe

### ISSUE THREAD

**Issue by mateusfsilva** [zino-app/graphql-flutter#690] opened 2020-07-20 13:17 UTC
I tried to use a subscription with the v4 alpha version and it didn't connect. I didn't receive any errors or exceptions. The connection just closes.
I can connect to this same subscription using version `graphql_flutter: ^3.0.1`.

Using version v3 I have the following sequence::

The client send:
``` json
{
  "type": "connection_init",
  "payload": {
    "authToken": "SOME_TOKEN"
  }
}
``` 
```json
{
  "type": "start",
  "id": "59f79e75-9181-4f8a-b31e-abf6322b2f64",
  "payload": {
    "operationName": "notifications",
    "query": "MY_QUERY",
    "variables": {}
  }
}
```

The server response:
``` json
{
  "type": "connection_ack"
}
```
``` json
{
  "type": "ka"
}
```
``` json
{
  "type": "data",
  "data": {
    "MY_DATA": []
  }
}
```

With v4 the client send:

```json
{
  "type": "connection_init",
  "payload": {
    "authToken": "SOME_TOKEN"
  }
}
```
```json
{
  "type": "start",
  "id": "92818936-2d7d-4e60-aff1-c217275210c9",
  "payload": {
    "operationName": "prices",
    "variables": {},
    "query": "MY_QUERY"
  }
}
```

And the connection closes.

I'm using the version:
```
  graphql_flutter: ^4.0.0-alpha.1
  graphql: ^4.0.0-alpha.1
```

Flutter version:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale pt-BR)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

Is anyone using a subscription with version v4?

**Comment by micimize** [comment] 2020-07-20 21:24
how are you passing connection init? There was a regression earlier in the init payload callback api, might not be resolved

**Comment by mateusfsilva** [comment] 2020-07-20 21:40
I used this code.

```dart
final AuthLink authLink = AuthLink(
  getToken: () async => Future<String>.value(
    'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
  ),
);

final Link linkAuth = authLink.concat(httpLink);

final WebSocketLink websocketLink = WebSocketLink(
  websocketAddress,
  initialPayload: <String, dynamic>{
    'authToken': YOUR_PERSONAL_ACCESS_TOKEN,
  },
);

final Link linkWebSocket = websocketLink.concat(authLink);

GraphQLClient(
  link: newLink,
  cache: widget.cache,
);
```

The cache was:
```dart
GraphQLCache(
  store: await HiveStore.open(),
);
```

But the connection_init is passing the token correctly. This value doesn't come from the payload?

**Comment by micimize** [comment] 2020-07-21 00:57
@mateusfsilva no it does – I think the issue is you need to split the link:
https://github.com/zino-app/graphql-flutter/blob/1275c1066aa051ab109cba19e42cb959aeb420cc/examples/starwars/lib/client_provider.dart#L27

**Comment by mateusfsilva** [comment] 2020-07-21 01:26
I already tried this:

```dart
    final HttpLink httpLink = HttpLink(
      graphQlAddress,
    );

    final AuthLink authLink = AuthLink(
      getToken: () async => Future<String>.value(
        'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
      ),
    );

    final Link linkAuth = authLink.concat(httpLink);

    final WebSocketLink websocketLink = WebSocketLink(
      websocketAddress,
      initialPayload: <String, dynamic>{
        'authToken': YOUR_PERSONAL_ACCESS_TOKEN,
      },
    );

    final Link linkWebSocket = websocketLink.concat(authLink);

    final Link newLink = Link.split(
      (Request request) => request.isSubscription,
      linkWebSocket,
      linkAuth,
    );

    client = GraphQLClient(
      link: newLink,
      cache: widget.cache,
    );
```

And this:

```dart
final HttpLink httpLink = HttpLink(
      graphQlAddress,
    );

    final AuthLink authLink = AuthLink(
      getToken: () async => Future<String>.value(
        'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
      ),
    );

    final Link linkAuth = authLink.concat(httpLink);

    final WebSocketLink websocketLink = WebSocketLink(
      websocketAddress,
      initialPayload: <String, dynamic>{
        'authToken': YOUR_PERSONAL_ACCESS_TOKEN,
      },
    );

    final Link newLink = Link.split(
      (Request request) => request.isSubscription,
      websocketLink,
      linkAuth,
    );

    client = GraphQLClient(
      link: newLink,
      cache: widget.cache,
    );
```

**Comment by micimize** [comment] 2020-07-21 01:44
@mateusfsilva ok – last one should work. Why is one operationName `notifications` and the other `prices`? If that isn't the issue then it's probably a bug, but we'll need more info to figure out exactly what's going on

**Comment by mateusfsilva** [comment] 2020-07-21 01:53
When I logged the v3 I logged another query.
I can create a repository with a full project if it helps

**Comment by micimize** [comment] 2020-08-14 18:59
@mateusfsilva if you could make a reproduction with an accessible server that'd be really helpful. I just realized that `gql_websocket_link` removed keep alive timeouts and auto reconnection so idk if that could have something to do with it https://github.com/gql-dart/gql/issues/129

**Comment by micimize** [comment] 2020-09-06 17:05
Try `4.0.0-alpha.4`, which adds back an updated version of the previous `WebSocketLink`.

Am intending to close this if we don't have a reproduction next week, as the new `WebSocketLink` is entirely different.

**Comment by micimize** [comment] 2020-09-12 17:37
closing for now. If anyone reproduces this issue with `^4.0.0-alpha.4` please comment or open another issue, ideally with a publicly accessible reproduction

**Closed by micimize** 2020-09-12 17:37 UTC
Labels: v4
