### ISSUE TITLE
Query refetch not working

### ISSUE THREAD

**Issue by Wisdom0063** [zino-app/graphql-flutter#346] opened 2019-06-24 17:24 UTC
```Query(
  options: QueryOptions(
    document: readRepositories, // this is the query string you just created
    variables: {
      'nRepositories': 50,
    },
    pollInterval: 10,
  ),
  // Just like in apollo refetch() could be used to manually trigger a refetch
  builder: (QueryResult result, { VoidCallback refetch }) {
    if (result.errors != null) {
      return Text(result.errors.toString());
    }

    if (result.loading) {
      return Text('Loading');
    }

    // it can be either Map or List
    List repositories = result.data['viewer']['repositories']['nodes'];

    return ListView.builder(
      itemCount: repositories.length,
      itemBuilder: (context, index) {
        final repository = repositories[index];

     return  FloatingActionButton(
        onPressed: refetch(),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      )
    });
  },
);```
 I calling refetch() but I am not seeing the output

**Comment by lucasavila00** [comment] 2019-06-26 20:52
I haven't had this problem. It would be useful if you could provide a better reproduction. Try to base it on the example of this project and maybe one would help.

**Comment by Wisdom0063** [comment] 2019-06-26 22:13
this is my code
``` return Query(
                            options: QueryOptions(
                                document: getUserprofile,
                                variables: {"user_id": userId},
                            ),
                            builder: (QueryResult nResult, {VoidCallback refetch}) {
                                if(nResult.loading == false) {
                                    if(nResult.data != null) {
                                        nData = nResult.data["getUserProfile"]["on_the_menu"];
                                        var tz =  nData.where((value)=>value["_id"] == widget.recipeIdRP);
                                        return Stack(
                                            children: <Widget>[
                                                Container(
                                                    child: CustomScrollView(
                                                        slivers: <Widget>[
                                                            SliverPersistentHeader(
                                                                pinned: true,
                                                                delegate: RecipeHeader(
                                                                    minExtent: ScreenUtil.instance.setHeight(450),
                                                                    maxExtent: ScreenUtil.instance.setHeight(450),
                                                                    recipeImage: data["pictures"][0],
                                                                    recipeName: data["name"],
                                                                    recipeTime: data["time"],
                                                                    recipeLevel: data["difficulty_level"],
                                                                    recipeServing: data["number_of_servings"],
                                                                    recipePercentage: data["ingredients_percentage"],
                                                                    isRecipeLiked: IconButton(
                                                                        icon: nData.where((value)=>value["_id"] == widget.recipeIdRP).isNotEmpty ? Image.asset(
                                                                            likeRecipe,
                                                                        ) : Image.asset(
                                                                            unlikeRecipe,
                                                                        ),
                                                                        iconSize: ScreenUtil.instance.setHeight(40),
                                                                        splashColor: Colors.transparent,
                                                                        onPressed: () {
                                                                            if(nData.where((value)=>value["_id"] == widget.recipeIdRP).isNotEmpty) {
                                                                                removeMenu();
                                                                                return refetch();
                                                                            } else {
                                                                                addMenu();
                                                                          return refetch();

                                                                            }
                                                                        },
                                                                    )
                                                                ),
                                                            ),
                                                            SliverList(
                                                                delegate: SliverChildBuilderDelegate((BuildContext context, int index) {
                                                                    return Column(
                                                                        children: <Widget>[
                                                                            Container(
                                                                                width: fullWidth,
                                                                                //height: ScreenUtil.instance.setHeight(250),
                                                                                child: Padding(
                                                                                    padding: EdgeInsets.only(
                                                                                        left: ScreenUtil.instance.setWidth(20),
                                                                                        top: ScreenUtil.instance.setHeight(20),
                                                                                        right: ScreenUtil.instance.setWidth(20),
                                                                                        bottom: ScreenUtil.instance.setHeight(20)
                                                                                    ),
                                                                                    child: Container(
                                                                                        constraints: BoxConstraints(
                                                                                            minHeight: ScreenUtil.instance.setHeight(5),
                                                                                            minWidth: ScreenUtil.instance.setWidth(600),
                                                                                            maxWidth: ScreenUtil.instance.setWidth(600)
                                                                                        ),
                                                                                        child: Text(
                                                                                            data["about_recipe"],
                                                                                            maxLines: 10,
                                                                                            overflow: TextOverflow.ellipsis,
                                                                                            style: TextStyle(
                                                                                                fontFamily: 'Montserrat',
                                                                                                fontSize: ScreenUtil.instance.setSp(22),
                                                                                                fontWeight: FontWeight.normal,
                                                                                                color: Color(0xFF8A8A8A)
                                                                                            ),
                                                                                        ),
                                                                                    ),
                                                                                ),
                                                                            ),
                                                                            Container(
                                                                                height: ScreenUtil.instance.setHeight(150),
                                                                                child: ListView(
                                                                                    scrollDirection: Axis.horizontal,
                                                                                    children: recipeCommentCard
                                                                                ),
                                                                            ),
                                                                            Padding(
                                                                                padding: EdgeInsets.only(
                                                                                    left: ScreenUtil.instance.setWidth(37),
                                                                                    top: ScreenUtil.instance.setHeight(20),
                                                                                    right: ScreenUtil.instance.setWidth(37),
                                                                                    bottom: ScreenUtil.instance.setHeight(20)
                                                                                ),
                                                                                child: Container(
                                                                                    width: fullWidth,
                                                                                    height: ScreenUtil.instance.setHeight(78),
                                                                                    decoration: BoxDecoration(
                                                                                        color: Colors.white,
                                                                                        borderRadius: BorderRadius.circular(ScreenUtil.instance.setHeight(78)/2),
                                                                                        boxShadow: <BoxShadow>[
                                                                                            BoxShadow(
                                                                                                color: Colors.black54,
                                                                                                offset: Offset(0.0, 1.0),
                                                                                                blurRadius: 4,
                                                                                            ),
                                                                                        ]
                                                                                    ),
                                                                                    child: Row(
                                                                                        mainAxisAlignment: MainAxisAlignment.spaceAround,
                                                                                        mainAxisSize: MainAxisSize.min,
                                                                                        children: <Widget>[
                                                                                            InkWell(
                                                                                                onTap: () {
                                                                                                    setState(() {
                                                                                                        isIngredientsSelected = true;
                                                                                                        isStepByStepSelected = false;
                                                                                                    });

                                                                                                    _selectedIndex = 0;
                                                                                                },
                                                                                                child: ActionBarChoice(
                                                                                                    "Ingredients",
                                                                                                    isIngredientsSelected,
                                                                                                ),
                                                                                            ),
                                                                                            InkWell(
                                                                                                onTap: () {
                                                                                                    setState(() {
                                                                                                        isIngredientsSelected = false;
                                                                                                        isStepByStepSelected = true;
                                                                                                    });

                                                                                                    _selectedIndex = 1;
                                                                                                },
                                                                                                child: ActionBarChoice(
                                                                                                    "Step by step",
                                                                                                    isStepByStepSelected,
                                                                                                ),
                                                                                            )
                                                                                        ],
                                                                                    ),
                                                                                ),
                                                                            ),
                                                                            Container(
                                                                                width: fullWidth,
                                                                                height: ScreenUtil.instance.setHeight(570),
                                                                                decoration: BoxDecoration(
                                                                                    color: Theme.of(context).backgroundColor,
                                                                                    borderRadius: BorderRadius.only(
                                                                                        topLeft: Radius.circular(40),
                                                                                        topRight: Radius.circular(40),
                                                                                    ),
                                                                                    boxShadow: <BoxShadow>[
                                                                                        BoxShadow(
                                                                                            color: Colors.black54,
                                                                                            offset: Offset(0.0, 1.0),
                                                                                            blurRadius: 2,
                                                                                        ),
                                                                                    ]
                                                                                ),
                                                                                child: _recipePageOptions.elementAt(_selectedIndex),
                                                                            ),
                                                                        ],
                                                                    );
                                                                },
                                                                    childCount: 1,
                                                                ),
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                                /*SlidingUpPanel(
                                    minHeight: ScreenUtil.instance.setHeight(253),
                                    maxHeight: ScreenUtil.instance.setHeight(525),
                                    borderRadius: BorderRadius.only(
                                        topLeft: Radius.circular(ScreenUtil.instance.setHeight(50)),
                                        topRight: Radius.circular(ScreenUtil.instance.setHeight(50)),
                                    ),
                                    panel: _recipePageOptions.elementAt(_selectedIndex),
                                )*/
                                            ],
                                        );
                                    } else {
                                        return Container();
                                    }

                                } else {
                                    return Container(
                                        height: ScreenUtil.instance.setHeight(1136),
                                        child: Center(
                                            child: PageLoader(),
                                        ),
                                    );
                                }
                            }
                        );```

**Comment by Wisdom0063** [comment] 2019-06-26 22:16
This is sample of my code where I am using a refetch()
```                        return Query(
                            options: QueryOptions(
                                document: getUserprofile,
                                variables: {"user_id": userId},
                            ),
                            builder: (QueryResult nResult, {VoidCallback refetch}) {
                              var refetchProfile = refetch;
                                if(nResult.loading == false) {
                                    if(nResult.data != null) {
                                        nData = nResult.data["getUserProfile"]["on_the_menu"];
                                        var tz =  nData.where((value)=>value["_id"] == widget.recipeIdRP);
                                        return Stack(
                                            children: <Widget>[
                                                Container(
                                                    child: CustomScrollView(
                                                        slivers: <Widget>[
                                                            SliverPersistentHeader(
                                                                pinned: true,
                                                                delegate: RecipeHeader(
                                                                    minExtent: ScreenUtil.instance.setHeight(450),
                                                                    maxExtent: ScreenUtil.instance.setHeight(450),
                                                                    recipeImage: data["pictures"][0],
                                                                    recipeName: data["name"],
                                                                    recipeTime: data["time"],
                                                                    recipeLevel: data["difficulty_level"],
                                                                    recipeServing: data["number_of_servings"],
                                                                    recipePercentage: data["ingredients_percentage"],
                                                                    isRecipeLiked: IconButton(
                                                                        icon: nData.where((value)=>value["_id"] == widget.recipeIdRP).isNotEmpty ? Image.asset(
                                                                            likeRecipe,
                                                                        ) : Image.asset(
                                                                            unlikeRecipe,
                                                                        ),
                                                                        iconSize: ScreenUtil.instance.setHeight(40),
                                                                        splashColor: Colors.transparent,
                                                                        onPressed: () {
                                                                            if(nData.where((value)=>value["_id"] == widget.recipeIdRP).isNotEmpty) {
                                                                                removeMenu();
                                                                                return refetchProfile();
                                                                            } else {
                                                                                addMenu();
                                                                          return refetchProfile();

                                                                            }
                                                                        },
                                                                    )
                                                                ),
                                                            ),```

**Comment by Wisdom0063** [comment] 2019-06-26 22:21
I have been following the documentation but it isnt working for me. Does a portion of my code where I used the refetch(). Everything else is working except that

**Comment by JeffersonCarvalh0** [comment] 2019-06-27 12:30
I'm also experiencing a similar issue. I'm trying to use refetch with the `RefreshIndicator` widget, but new data isn't being fetched

**Comment by guilhermedecampo** [comment] 2019-06-27 13:01
@lucasavila00 	can you add here the snippet that works for you?

**Comment by micimize** [comment] 2019-06-27 14:32
My best guess is that there's some issue with the observable query `lifecycle` updating in your specific scenario. Please provide more details, like `fetchPolicy` and possibly the `lifecycle` when you break the debugger on `refetch()` and descend into it's context

Also, if you're results get populated from the cache first, maybe it'll work after the first network request completes.

Also, format your code snippets. And I assume you meant this in your first example
```diff
return FloatingActionButton(
- onPressed: refetch(),
+ onPressed: refetch,
  tooltip: 'Increment',
  child: Icon(Icons.add),
)
```

This is the refetch code in `observable_query.dart` I think is suspect:
```dart
  bool get _isRefetchSafe {
    switch (lifecycle) {
      case QueryLifecycle.COMPLETED:
      case QueryLifecycle.POLLING:
      case QueryLifecycle.POLLING_STOPPED:
        return true;

      case QueryLifecycle.PENDING:
      case QueryLifecycle.CLOSED:
      case QueryLifecycle.UNEXECUTED:
      case QueryLifecycle.SIDE_EFFECTS_PENDING:
      case QueryLifecycle.SIDE_EFFECTS_BLOCKING:
        return false;
    }
    return false;
  }

  /// Attempts to refetch, returning `true` if successful
  bool refetch() {
    if (_isRefetchSafe) {
      queryManager.refetchQuery(queryId);
      return true;
    }
    return false;
  }
```

**Comment by Wisdom0063** [comment] 2019-06-27 14:44
I didn't provide any fetchPolicy in my code. So I guess I am using the default

**Comment by JeffersonCarvalh0** [comment] 2019-07-04 11:56
@micimize I debugged the code here, and could state that my query lifecicle is `PENDING` and my fetch policy is `cacheAndNetwork`. What can possibly the issue in this case?

**Comment by JeffersonCarvalh0** [comment] 2019-07-04 13:18
Even when my `fetchPolicy` is `networkOnly`, the status keeps `PENDING`

**Comment by micimize** [comment] 2019-07-04 21:08
@JeffersonCarvalh0 to clarify, you:
1. run a query with `fetchPolicy=networkOnly`
2. get results from the network, no logged errors, the component renders with data
3. attempt to refetch, but `lifecycle=PENDING`, so it fails?

If so, this is likely a regression

**Comment by JeffersonCarvalh0** [comment] 2019-07-05 11:23
Exactly. The query that is performed when the widget is built works perfectly. The problem only happens when I try to refetch.

**Comment by Wisdom0063** [comment] 2019-07-05 13:07
@JeffersonCarvalh0  I needed to be able to refetch so I found a hack around pollInterval. I initially set pollInterval to null so when the person clicks on the button to refetch I call setState to change pollInterval to say 2. So after the request is successful I call setState again to change pollInterval to null . It is not the best  of idea but for now don't have any option

**Comment by JeffersonCarvalh0** [comment] 2019-07-05 13:18
Thanks, @Wisdom0063, it worked like a charm here!

**Comment by guilhermedecampo** [comment] 2019-07-14 10:14
@mainawycliffe 	this is still a problem. Why did you close the issue? Do we have a PR fixing it?

What they guys did was just a workaround.

**Comment by mainawycliffe** [comment] 2019-07-14 10:21
@guilhermedecampo I am sorry. Thought it was resolved, judging by the last comment. I am reopening it, will look in to it over the week. Can you reproduce the issue on a small repo, may be using the GitHub API?

**Comment by serendipity1004** [comment] 2019-10-29 08:26
@mainawycliffe any directions for this? like @Wisdom0063 said, lifecycle is always pending so refetch is always unsafe. If you are too busy, just point me to right direction and I'll try to find the root cause.

**Comment by mainawycliffe** [comment] 2019-10-29 09:19
@serendipity1004 this completely slipped under my radar, I am sorry about that. I will look into it in the course of the week and share my thoughts on the way forward.

**Comment by guilhermedecampo** [comment] 2019-10-29 14:07
amazing @mainawycliffe

**Comment by mainawycliffe** [comment] 2019-11-06 23:17
@serendipity1004 I can't still reproduce this error with the examples we have, though I am using the latest version which is yet to release. `refetch` is working as expected as far as I can tell If I can't reproduce the issue I can't debug it. Maybe it was fixed inadvertently by a previous PR, can someone please confirm if they are still getting the same error using the latest beta.

**Comment by mainawycliffe** [comment] 2019-11-06 23:18
A repo reproducing the issue would be very useful, this way I can jump right in to debug the issue.

**Comment by onemanstartup** [comment] 2019-11-06 23:51
For me, it's working with the latest beta.

**Closed** 2019-11-07 15:30 UTC
Labels: bug, flutter, good first issue, help wanted

**Comment by blaugold** [comment] 2020-11-11 09:18
I just ran into a related problem, I think. 

I have a watch query which uses `FetchPolicy.cacheFirst` and I want to use `refetch` at some later point to refresh the query. The problem is that the `ObservableQuery` is getting stuck in `QueryLifecycle.pending` after the initial call to `fetchResults` and throws when calling `refetch`. 

I suspect the root cause is in the order of the call to `fetchQueryAsMultiSourceResult` and setting `lifecycle`. If the query has eager results, `fetchQueryAsMultiSourceResult` will synchronously trigger a call to `addResult`, which is responsible for setting `lifecycle` to `QueryLifecycle.completed`. Then `lifecycle` is set to `QueryLifecycle.pending`, but without a network request 
lifecycle is never updated again.

```dart
  MultiSourceResult fetchResults() {
    final MultiSourceResult allResults =
        queryManager.fetchQueryAsMultiSourceResult(queryId, options);
    latestResult ??= allResults.eagerResult;

    // if onData callbacks have been registered,
    // they are waited on by default
    lifecycle = _onDataCallbacks.isNotEmpty
        ? QueryLifecycle.sideEffectsPending
        : QueryLifecycle.pending;

    if (options.pollInterval != null && options.pollInterval > Duration.zero) {
      startPolling(options.pollInterval);
    }

    return allResults;
  }
```

**Comment by micimize** [comment] 2020-11-11 14:46
@blaugold I'd consider this a different issue, but based on what you're saying it seems unlikely to me that you need to refetch. Any changes to the underlying data in the cache will trigger a rebroadcast on the observable query automatically,`refetch` only refetches from the network, overriding the `fetchPolicy` because there is never a reason to `refetch` from the cache:
https://github.com/zino-app/graphql-flutter/blob/2efce9f15e59208d86a2c4b1c9e0794cc28ea680/packages/graphql/lib/src/core/query_manager.dart#L294-L308

Might be a bit different on `master` – I recommend switching to `beta` if you aren't already on it

**Comment by blaugold** [comment] 2020-11-11 15:30
@micimize Thanks for all the work on this package. I would like to use only the cache if the data is available and let the user trigger a refresh from the server whenever they want to. I thought that was possible with a combination of `FetchPolicy.cacheFirst` and `refetch`. Am I missing something?

**Comment by micimize** [comment] 2020-11-12 14:54
@blaugold no that's correct – I misunderstood you, now I see what you were saying. I think you're correct. Made #771 to track it
