### ISSUE TITLE
HiveStore Async Usage Example / Simplification

### ISSUE THREAD

**Issue by lazylazyllama** [zino-app/graphql-flutter#674] opened 2020-06-19 11:39 UTC
**Describe the issue**
If I use HiveStore.open() as my GraphQLCache, i have to await it first. So I have to do that in an async context. But GraphQLProvider does not want a Future. So how can I do that.

**Comment by micimize** [comment] 2020-06-19 14:16
You can use a [`FutureBuilder`](https://api.flutter.dev/flutter/widgets/FutureBuilder-class.html) for now –this is definitely an oversight caused by me not using the recommended `Store` in any of the examples 🤦

**Comment by micimize** [comment] 2020-06-19 16:08
@lazylazyllama am going to have to rethink the current api, but for now you can do something like:
```dart
void main() async {
  await Hive.initFlutter(); // or await initHiveForFlutter();
  await Hive.openBox(HiveStore.defaultBoxName);
  runApp(MyApp());
}

/// then, at your cache declaration
cache = GraphQLCache(
  store: HiveStore(
      Hive.box(HiveStore.defaultBoxName),
    ),
  ),
);
```
This initializes ("opens") the box in `main`, for eager resolution later.

Will probably end up implementing an api like the following:
```dart
Future<void> initHiveForFlutter(Iterable<String> withBoxes = [ HiveStore.defaultBoxName ])
...
/// default constructor
HiveStore([ Box box ]): this.box = box ?? Hive.box(defaultBoxName);
```

**Comment by micimize** [comment] 2020-07-25 02:11
https://pub.dev/packages/graphql/versions/4.0.0-alpha.2 includes a revamped api for `HiveStore`, closing this:

```dart
/// Only necessary on flutter
void main() async {
  await initHiveForFlutter();
  runApp(MyApp());
}

GraphQLCache(
  // The default store is the InMemoryStore, which does NOT persist to disk
  store: GraphQLCache(store: HiveStore()),
)
```

**Closed by micimize** 2020-07-25 02:11 UTC
Labels: v4

**Comment by subhendukundu** [comment] 2020-11-03 14:37
I have gotten an error on hot reload with the latest beta `graphql_flutter: 4.0.0-beta.3`.
```
The following HiveError was thrown building ClientProvider(dirty):
Box not found. Did you forget to call Hive.openBox()?

The relevant error-causing widget was
ClientProvider
lib/main.dart:29
When the exception was thrown, this was the stack
#0      HiveImpl._getBoxInternal
package:hive/src/hive_impl.dart:170
#1      HiveImpl.box
package:hive/src/hive_impl.dart:181
#2      new HiveStore
package:graphql/…/cache/hive_store.dart:40
#3      ClientProvider.build.clientFor
package:epics/graphql_provider.dart:56
#4      ClientProvider.build

```

I am using the `main()` like 
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  setupLocator();
  await initHiveForFlutter();

  runApp(App());
}
```

Also 
```
return ValueNotifier<GraphQLClient>(
        GraphQLClient(
          cache: GraphQLCache(
            store: HiveStore(),
          ),
          link: link,
        ),
 );
```

How do I fix this issue?

**Comment by micimize** [comment] 2020-11-03 15:25
@subhendukundu I think it might have something to do with `get_it` usage (based on `setupLocator`), or maybe something isn't being disposed properly? Our [`initHiveForFlutter`](https://github.com/zino-app/graphql-flutter/blob/beta/packages/graphql_flutter/lib/src/hive_init.dart) is a fairly direct rip from [`Hive.initFlutter`](https://github.com/hivedb/hive/blob/5bf355496650017409fef4e9905e8826c5dc5bf3/hive_flutter/lib/src/hive_extensions.dart), and I can't find any related issues for hive itself.

If you want to try pasting your `ClientProvider` I could take a closer look, or look around for issues with [`get_it` and flutter hot reload](https://stackoverflow.com/questions/58326960/flutter-get-it-and-futurebuilder-not-working-with-hot-reload)

**Comment by subhendukundu** [comment] 2020-11-03 15:34
Umm could be an issue of rerendering the ClientProvider when the firebase auth token is back?
```
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:flutter/material.dart';

String uuidFromObject(Object object) {
  if (object is Map<String, Object>) {
    final String typeName = object['__typename'] as String;
    final String id = object['id'].toString();
    if (typeName != null && id != null) {
      return <String>[typeName, id].join('/');
    }
  }
  return null;
}

class ClientProvider extends StatelessWidget {
  final Widget child;
  final String uri;
  final String subscriptionUri;
  final String token;

  ClientProvider({
    @required this.child,
    @required this.uri,
    this.subscriptionUri,
    this.token,
  });

  @override
  Widget build(BuildContext context) {
    ValueNotifier<GraphQLClient> clientFor({
      @required String uri,
      String subscriptionUri,
    }) {
      Link httpLink = HttpLink(uri);
      if (subscriptionUri != null) {
        final WebSocketLink websocketLink = WebSocketLink(
          subscriptionUri,
        );

        httpLink = Link.split(
            (request) => request.isSubscription, websocketLink, httpLink);
      }

      final authLink = AuthLink(
        getToken: () async => 'Bearer $token',
      );

      var link = authLink.concat(httpLink);

      return ValueNotifier<GraphQLClient>(
        GraphQLClient(
          cache: GraphQLCache(
            store: HiveStore(),
          ),
          link: link,
        ),
      );
    }

    final ValueNotifier<GraphQLClient> client = clientFor(
      uri: uri,
      subscriptionUri: subscriptionUri,
    );

    return GraphQLProvider(
      client: client,
      child: child,
    );
  }
}
```
And using it in `main.dart` like
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  setupLocator();
  await initHiveForFlutter();

  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder.reactive(
      viewModelBuilder: () => AppViewModel(),
      onModelReady: (model) => model.getIdToken(),
      builder: (context, model, child) => ClientProvider(
        uri: '$GRAPHQL_BASE_API/v1/graphql',
        subscriptionUri: '$GRAPHQL_WSS_API/v1/graphql',
        token: model.token,
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'App',
          themeMode: model.themeMode,
          theme: model.themeData,
          navigatorKey: locator<NavigationService>().navigatorKey,
          onGenerateRoute: MainRouter().onGenerateRoute,
          initialRoute: Routes.splashView,
        ),
      ),
    );
  }
}

class AppViewModel extends ReactiveViewModel {
  final _authService = locator<AuthService>();
  final _themeService = locator<ThemeService>();

  ThemeMode get themeMode => _themeService.theme;
  ThemeData get themeData => _themeService.isLight
      ? _themeService.lightTheme
      : _themeService.darkTheme;

  String _token = '';

  String get token => _token;

  getIdToken() async {
    final idToken = await _authService.getIdToken();
    _token = idToken;
    notifyListeners();
  }

  @override
  List<ReactiveServiceMixin> get reactiveServices => [_themeService];
}
```

**Comment by micimize** [comment] 2020-11-03 15:49
@subhendukundu could be – I'm not _that_ confident that it is, but try:
```dart
void main() async {
  await initHiveForFlutter(); // calls WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  setupLocator();

  runApp(App());
}
```
And maybe then see if hot reload works without using the `ViewModelBuilder.reactive`. If not, then there could be an issue with how we're doing things
