### ISSUE TITLE
Subscription, can use it without using subscription widgets？

### ISSUE THREAD

**Issue by chenxianqi** [zino-app/graphql-flutter#231] opened 2019-04-22 14:37 UTC
I want to open subscriptions programmatically. How do I write them?hope it's the same as queries. don't know how to write it.
```
    QueryResult result = await minProvide.graphqlClient.value.query(QueryOptions(
      document:  Queries.getHomeAppBanners,
      variables: {"timer":"${DateTime.now().millisecondsSinceEpoch}"}
    ));
```

**Comment by mainawycliffe** [comment] 2019-04-22 15:02
Yes it is possible. You can check this example here using bloc https://github.com/zino-app/graphql-flutter/blob/master/example/lib/graphql_bloc/bloc.dart

**Comment by chenxianqi** [comment] 2019-04-23 00:52
> Yes it is possible. You can check this example here using bloc https://github.com/zino-app/graphql-flutter/blob/master/example/lib/graphql_bloc/bloc.dart

How to use subscription (Socket) in bloc?

**Comment by mainawycliffe** [comment] 2019-04-23 00:59
You mean `flutter_bloc`?

**Comment by chenxianqi** [comment] 2019-04-23 01:04
> You mean `flutter_bloc`?

I want to use it anywhere, No dependence Subscription widget

**Comment by mainawycliffe** [comment] 2019-04-23 01:14
You first need to create a `GraphQLClient` just like in a widget:

```dart
static final HttpLink _httpLink = HttpLink(
  uri: 'https://api.github.com/graphql',
);

static final AuthLink _authLink = AuthLink(
  getToken: () async => 'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
);

static final Link _link = _authLink.concat(_httpLink as Link);

static final GraphQLClient _client = GraphQLClient(
  cache: NormalizedInMemoryCache(
    dataIdFromObject: typenameDataIdFromObject,
  ),
  link: _link,
);
```

Then run the query:

```dart
final QueryResult result = await _client.query(_options);
```
Or mutation:

```dart
final QueryResult result = await _client.mutate(_options);
```

And then you can use the results, which is exactly the same as what you get when using the widget method.

**Comment by chenxianqi** [comment] 2019-04-23 01:17
> You first need to create a `GraphQLClient` just like in a widget:
> 
> ```dart
> static final HttpLink _httpLink = HttpLink(
>   uri: 'https://api.github.com/graphql',
> );
> 
> static final AuthLink _authLink = AuthLink(
>   getToken: () async => 'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
> );
> 
> static final Link _link = _authLink.concat(_httpLink as Link);
> 
> static final GraphQLClient _client = GraphQLClient(
>   cache: NormalizedInMemoryCache(
>     dataIdFromObject: typenameDataIdFromObject,
>   ),
>   link: _link,
> );
> ```
> 
> Then run the query:
> 
> ```dart
> final QueryResult result = await _client.query(_options);
> ```
> 
> Or mutation:
> 
> ```dart
> final QueryResult result = await _client.mutate(_options);
> ```
> 
> And then you can use the results, which is exactly the same as what you get when using the widget method.


I'm sorry, I said that. （Subscriptions (Experimental)） ，My description may not be clear enough.

**Comment by chenxianqi** [comment] 2019-04-23 01:17
> > You first need to create a `GraphQLClient` just like in a widget:
> > ```dart
> > static final HttpLink _httpLink = HttpLink(
> >   uri: 'https://api.github.com/graphql',
> > );
> > 
> > static final AuthLink _authLink = AuthLink(
> >   getToken: () async => 'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
> > );
> > 
> > static final Link _link = _authLink.concat(_httpLink as Link);
> > 
> > static final GraphQLClient _client = GraphQLClient(
> >   cache: NormalizedInMemoryCache(
> >     dataIdFromObject: typenameDataIdFromObject,
> >   ),
> >   link: _link,
> > );
> > ```
> > 
> > 
> > Then run the query:
> > ```dart
> > final QueryResult result = await _client.query(_options);
> > ```
> > 
> > 
> > Or mutation:
> > ```dart
> > final QueryResult result = await _client.mutate(_options);
> > ```
> > 
> > 
> > And then you can use the results, which is exactly the same as what you get when using the widget method.
> 
> I'm sorry,What I'm talking about is （Subscriptions (Experimental)） ，My description may not be clear enough.

**Comment by mainawycliffe** [comment] 2019-04-23 01:35
Sorry, about that. Am guessing, it should be something like this:

```dart
SocketClient socketClient = SocketClient('ws://coolserver.com/graphql');
```

And then subscribe:

```dart
Stream<SubscriptionData> data = socketClient.subscribe(payload, waitForConnection)
```

**Comment by chenxianqi** [comment] 2019-04-23 01:37
> 对于那个很抱歉。我猜，它应该是这样的：
> 
> ```dart
> SocketClient socketClient =  SocketClient（'ws：//coolserver.com/graphql'）;
> ```
> 
> 然后订阅：
> 
> ```dart
> Stream < SubscriptionData > data = socketClient。subscribe（payload，waitForConnection）
> ```

Thank you. Let me try and see. Thank you again for your patient reply.

**Comment by chenxianqi** [comment] 2019-05-06 15:55
> Sorry, about that. Am guessing, it should be something like this:
> 
> ```dart
> SocketClient socketClient = SocketClient('ws://coolserver.com/graphql');
> ```
> 
> And then subscribe:
> 
> ```dart
> Stream<SubscriptionData> data = socketClient.subscribe(payload, waitForConnection)
> ```
·

**Comment by chenxianqi** [comment] 2019-05-06 16:02
> Sorry, about that. Am guessing, it should be something like this:
> 
> ```dart
> SocketClient socketClient = SocketClient('ws://coolserver.com/graphql');
> ```
> 
> And then subscribe:
> 
> ```dart
> Stream<SubscriptionData> data = socketClient.subscribe(payload, waitForConnection)
> ```

I can't connect to websocket

>  ```dart
>   SocketClient socketClient =  SocketClient(
>   Config.DEBUG ? Config.CABLE_DEV : Config.CABLE_RELEASE,
>    headers: {
>    'Authorization': "Bearer token:d60db42fa562e699"
>   },
>  );
>  SubscriptionRequest payload = SubscriptionRequest(Operation(
>     operationName: "onMessageSent",
>     document:  Subscriptions.onMessageSent,
>   ));
>   Stream <SubscriptionData> res = socketClient.subscribe(payload, true);
>   res.listen((data){
>        print(data.data);
>   });
>   ```

>   ```  console info
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...
I/flutter ( 9135): Disconnected from websocket.
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...
I/flutter ( 9135): Disconnected from websocket.
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...
I/flutter ( 9135): Disconnected from websocket.
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...
I/flutter ( 9135): Disconnected from websocket.
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...
I/flutter ( 9135): Disconnected from websocket.
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...
I/flutter ( 9135): Disconnected from websocket.
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...
I/flutter ( 9135): Disconnected from websocket.
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...
I/flutter ( 9135): Disconnected from websocket.
I/flutter ( 9135): Scheduling to connect in 5 seconds...
I/flutter ( 9135): Connecting to websocket: ws://meemeeapp.com/cable...

**Comment by mainawycliffe** [comment] 2019-05-06 20:05
Sorry, I don't have a readily available websocket graphql server at hand to give you a readily working solution. But i have been going through the code and i think you just need to replace `HttpLink` with `WebSocketLink` as shown below:

```dart
GraphQLClient client() {
  final WebSocketLink websocketLink = WebSocketLink(
    url: 'ws://localhost:8080/ws/graphql',
    config: SocketClientConfig(
        autoReconnect: true, inactivityTimeout: Duration(seconds: 15)),
  );

  final AuthLink _authLink = AuthLink(
    getToken: () async => 'Bearer $YOUR_PERSONAL_ACCESS_TOKEN',
  );

  final Link _link = _authLink.concat(websocketLink);

  return GraphQLClient(
    cache: InMemoryCache(),
    link: _link,
  );
}
```

I extracted that from the example [here](https://github.com/zino-app/graphql-flutter/blob/4576a80e23d4007f64aff57c1748a95510d7bce6/packages/graphql/example/bin/main.dart#L17) for connecting to the GraphQL with pure dart alone, which was using HTTP

**Comment by chenxianqi** [comment] 2019-05-07 00:56
Is my writing correct?
Still not connected

>```dart
>static GraphQLClient initWebSocketLink(){
>    final WebSocketLink websocketLink = WebSocketLink(
>      url:  Config.DEBUG ? Config.CABLE_DEV : Config.CABLE_RELEASE,
>      config: SocketClientConfig(
>        autoReconnect: true,
>        inactivityTimeout: Duration(seconds: 15),
>      ),
>    );
>   final AuthLink authLink = AuthLink(
>      getToken: () async => "Bearer token:d60db42fa562e699",
>    );
>    Link link = authLink.concat(websocketLink);
>    return GraphQLClient(
>      cache: InMemoryCache(),
>      link: link,
>    );
>  }
>```

use

>```dart
>    GraphQLClient client = Graphql.initWebSocketLink();
>    client.subscribe(Operation(
>      operationName: "onMessageSent",
>      document: Subscriptions.onMessageSent,
>    )).listen((onData){
>      print(onData);
>    }).onError((err){
>      print(err);
>    });
>```

**Comment by mainawycliffe** [comment] 2019-05-07 15:36
Everything seems in order. i will have to setup a Web Socket GraphQL Server to help you out and create a workable example. I hope i can sometime this week find sometime to do so.

**Comment by micimize** [comment] 2019-05-28 01:54
It uses `graphql_flutter` rather than `graphql/client.dart`, but the [`starwars` example](https://github.com/zino-app/graphql-flutter/blob/master/examples/starwars) has fully functioning subscriptions. It also uses an easily runnable [test server](https://github.com/micimize/angel-starwars-test-server), so @chenxianqi hopefully you can use it as a starting point for figuring out standalone subscriptions.

I'm closing this in favor of #169

**Closed by micimize** 2019-05-28 01:54 UTC
Labels: docs & examples

**Comment by bsr203** [comment] 2019-06-11 03:29
hi. I followed the starwars example, which works perfectly. In additions to http and ws, I also have an auth link. 
```
ValueNotifier<GraphQLClient> clientFor({
  @required String uri,
  @required String subscriptionUri,
}) {
  print(subscriptionUri);
  const token = '...';

  final AuthLink _authLink = AuthLink(
    getToken: () async => 'Bearer $token',
  );

  // Link _link = _authLink.concat(HttpLink(uri: uri) as Link);
  Link _link = HttpLink(uri: uri) as Link;

  if (subscriptionUri != null) {
    final WebSocketLink websocketLink = WebSocketLink(
      url: subscriptionUri,
      config: SocketClientConfig(
        autoReconnect: true,
        inactivityTimeout: Duration(seconds: 30),
      ),
    );

    print(subscriptionUri);
    _link = _link.concat(websocketLink);
  }

  _link = _authLink.concat(_link);

  return ValueNotifier<GraphQLClient>(
    GraphQLClient(
      cache: cache,
      link: _link,
    ),
  );
}
```

I played around with the order, to see which one apply first, but seems that instead of using ws link, my subscription request end up in http uri, so gets no operation error. 

How to get all these links work like; always apply auth link then Query + Mutation through http and subscription through ws link. 

thanks in advance.

**Comment by bsr203** [comment] 2019-06-11 12:28
The below code was causing issue for me
```
 bool get isSubscription =>
      operationName != null &&
      document.contains(RegExp(r'.*?subscription ' + operationName));
```

I guess, this impose a convention on naming the subscription.

**Comment by chenxianqi** [comment] 2019-06-19 13:36
I'm sorry that I don't have time to look at it. Thank you for your positive response.

**Comment by kevinrodriguez-io** [comment] 2019-09-10 07:16
> The[ below code](https://github.com/zino-app/graphql-flutter/blob/ced45b5b06bae3a43c2646d682f8b289675adc9e/packages/graphql/lib/src/link/operation.dart#L39) was causing issue for me
> 
> ```
>  bool get isSubscription =>
>       operationName != null &&
>       document.contains(RegExp(r'.*?subscription ' + operationName));
> ```
> 
> I guess, this impose a condition that operation name has to match in two instance. Below wont work
> 
> ```
> 
>  return Subscription<Map<String, dynamic>>(
>       'reviewAdded',
>       r'''
>         subscription ReviewAdded {
>           reviewAdded {
> ```
> 
> it is ok once figured out :-)

This solved the issue, **subscriptions must be named** ???
Now I do have an issue with my JWT Token; it appears not to be sent over the `WebSocketLink` because Hasura is giving me the following error:
```
/flutter (12547): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: {type: error, id: 2407fed3-0085-4307-abde-2c4f74a7ea02, payload: {extensions: {path: $, code: start-failed}, message: cannot start as connection_init failed with : Missing Authorization header in JWT authentication mode}}
```

**Comment by bsr203** [comment] 2019-09-10 13:17
@kevinrodriguez-io try to step over the code and log the http headers at the server. It does work for me though I use go server.

**Comment by razorabhu1995** [comment] 2020-05-13 07:14
I think my graphql client setup is fine:
`

     final HttpLink httpLink = HttpLink(
        uri: 'http://exampleurl.com/graphql',
     );

      final WebSocketLink websocketLink =
        WebSocketLink(
        url: 'ws://exampleurl.com/graphql',
          config: SocketClientConfig(
          autoReconnect: true,
          inactivityTimeout: Duration(seconds: 30),
        ),
      );

     final Link link = authLink.concat(httpLink).concat(websocketLink);

      ValueNotifier<GraphQLClient> client = ValueNotifier(GraphQLClient(
        link: link,
        cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
      ));
`
I don't know if there is something wrong with the way by using the subscription:

`
      Stream<FetchResult> subscriptionResult;
       StreamSubscription<FetchResult> streamSubscriptionResult;
   
    operation = Operation(documentNode: gql(messageSubscription), 
        variables : {
          'hash' : somehash
        }, operationName: 'message');

    subscriptionResult = globals.client.subscribe(operation);

    if(subscriptionResult != null){
      streamSubscriptionResult = subscriptionResult.listen((messages) {
        print("listening ${messages}");
      },
      onError: (e){
        print("error: $e");
      },
      cancelOnError: true);
      print("subscription result: ${streamSubscriptionResult}");
    }
`

The result:
`
I/flutter ( 8548): Connected to websocket.
I/flutter ( 8548): Disconnected from websocket.
I/flutter ( 8548): Scheduling to connect in 5 seconds...
`
Any solution???

**Comment by Vincent254** [comment] 2020-06-11 07:46
I/flutter ( 8548): Connected to websocket. I/flutter ( 8548): Disconnected from websocket. I/flutter ( 8548): Scheduling to connect in 5 seconds...

Hi .. Am also getting this error .. Did you get a solution for this

**Comment by Vincent254** [comment] 2020-06-11 07:47
I/flutter ( 8548): Connected to websocket. I/flutter ( 8548): Disconnected from websocket. I/flutter ( 8548): Scheduling to connect in 5 seconds...

Hi .. Am also getting this error .. Did you get a solution for this

**Comment by micimize** [comment] 2020-06-11 18:23
@Vincent254 & @razorabhu1995 this looks like a subscription is being opened but no data is being sent from the server. Those "Disconnected... scheduling to connect" logs are caused by the `inactivityTimeout`. If you're certain your server is sending messages on the websocket but they aren't arriving, open another issue with more details

**Comment by Vincent254** [comment] 2020-06-12 06:55
Hi Mic, i followed up on this and youre right. I simulated some load and was a ble to receive subscriptions. it means that the channel disconnects if theres no activity and will try to reconnect if the sicket config has recoonect set to true. Im fine with this for now

**Comment by comerc** [comment] 2020-10-27 12:24
@kevinrodriguez-io do you have solution for hasura with jwt?
