### ISSUE TITLE
[BUG] Version incompatible

### ISSUE THREAD

**Issue by lulumeimei** [zino-app/graphql-flutter#975] opened 2021-11-09 04:16 UTC
**Describe the issue**
Cannot install due to version incompatible

```dart
Because every version of pcari_chat from path depends on stream_chat_flutter ^3.2.0 which depends on rxdart ^0.27.0, every version of pcari_chat from path requires rxdart ^0.27.0.
And because graphql 5.0.0 depends on rxdart ^0.26.0 and no versions of graphql match >5.0.0 <6.0.0, pcari_chat from path is incompatible with graphql ^5.0.0.
So, because pcari_user depends on both graphql ^5.0.0 and pcari_chat from path, version solving failed.
Running "flutter pub get" in pcari-user-new...                          
pub get failed (1; So, because pcari_user depends on both graphql ^5.0.0 and pcari_chat from path, version solving failed.)
```

**Comment by xiprox** [comment] 2021-11-11 08:55
This seems to be a duplicate of #943.

As a quick solution, you can override the version of rxdart:
```yml
dependencies:
  ...

dependency_overrides:
  rxdart: ^0.27.0
```

**Comment by eugene-kalaganov** [comment] 2021-11-15 08:00
> This seems to be a duplicate of #943.
> 
> As a quick solution, you can override the version of rxdart:
there are huge differences and breaking changes between 26 and 27 versions 

it's impossible if you already have rxdart 0.27.0 in dependencies

**Comment by xiprox** [comment] 2021-11-15 16:25
> it's impossible if you already have rxdart 0.27.0 in dependencies

Not really. I depend on `rxdart: ^0.27.2` and `graphql: ^5.0.0`, and overriding `rxdart: ^0.27.2` works.

**Comment by eugene-kalaganov** [comment] 2021-11-15 16:33
it's because you don't use it, at least you don't use BehaviorSubjects

**Comment by vincenzopalazzo** [comment] 2021-11-21 09:49
Fixed with https://github.com/zino-app/graphql-flutter/pull/978

Thanks

**Closed by vincenzopalazzo** 2021-11-21 09:49 UTC
Labels: :bug: bug, :warning: duplicate
