### ISSUE TITLE
NoSuchMethodError (NoSuchMethodError: The getter 'host' was called on null

### ISSUE THREAD

**Issue by diegothucao** [zino-app/graphql-flutter#586] opened 2020-03-20 06:28 UTC
when we call api in case internet is off, it crash because of issue 
```
NoSuchMethodError (NoSuchMethodError: The getter 'host' was called on null
```
And seem we cannot catch exception.
Could you check on it?

**Comment by staaouat** [comment] 2020-03-20 17:52
I get the same problem by running the following demo:

====flutter run --verbose
[+3951 ms] E/flutter (23811): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'host' was called on null.


import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import './mutations.dart' as mutations;
import './queries.dart' as queries;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final HttpLink httpLink = HttpLink(
     uri:'https://countries.trevorblades.com/', 
    );

    final ValueNotifier<GraphQLClient> client = ValueNotifier<GraphQLClient>(
      GraphQLClient(
        cache: InMemoryCache(),
        link: httpLink,
      ),
    );

    
    return GraphQLProvider(
      client: client,
      child: CacheProvider(
        child: MaterialApp(
          title: 'GraphQL Flutter Demo',
          theme: ThemeData(
            primarySwatch: Colors.orange,
          ),
          home: MyHomePage(),
        ),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
   GraphQLConfiguration graphQLConfiguration = GraphQLConfiguration();
   var mq ='''
query Myquery {
  continents {
    name
  }
}
''';  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Hasura Vote'),
      ),
      body: Container(
        child: Query(
          options: QueryOptions(
            documentNode: gql(mq),
            pollInterval: 4,
          ),

          builder: (QueryResult result,
              {VoidCallback refetch, FetchMore fetchMore}) {
                if(result.data==null){
                  return   Text('data is null');
                }
            if (result.loading) {
              print('isloading');
              return const Center(
                child: CircularProgressIndicator(),
              );
            }

            if (result.hasException) {
              return Text('\nErrors: \n  ' + result.exception.toString());
            }

            // result.data can be either a [List<dynamic>] or a [Map<String, dynamic>]
            final List<dynamic> pls = result.data['programming_language'];

            return ListView.builder(
              itemCount: pls.length,
              itemBuilder: (BuildContext context, int index) {
                final Map<String, dynamic> pl = pls[index];
                final String name = pl["name"];
                final int voteCount = pl["vote_count"];

                return Mutation(
                  options: MutationOptions(
                    documentNode: gql(mutations.vote),
                  ),
                  builder: (
                    RunMutation vote,
                    QueryResult voteResult,
                  ) {
                    if (voteResult.data != null && voteResult.data.isNotEmpty) {
                      pl['vote_count'] = pl['vote_count'] + 1;
                    }

                    return ListTile(
                      title: Text('$name - $voteCount'),
                      trailing: Icon(Icons.thumb_up),
                      onTap: () {
                        vote(<String, String>{
                          'name': name,
                        });
                      },
                    );
                  },
                );
              },
            );
          },
        ),
      ),
    );
  }
 
}

**Comment by alinetskyi** [comment] 2020-03-22 14:09
I  also have the same issue!

**Comment by speller** [comment] 2020-03-23 14:53
This issue happens when host lookup failed:

![image](https://user-images.githubusercontent.com/1829515/77329435-5398ce80-6d61-11ea-8a87-e2fc3cafd583.png)

As you can see, the failure.address field is null.

**Comment by speller** [comment] 2020-03-23 15:08
As a temporary solution, you may manually edit the problematic line until we get an update from authors:
`host: failure.address != null ? failure.address.host : null,`

**Comment by knaeckeKami** [comment] 2020-03-24 09:44
this is already fixed on the current beta release  3.0.1-beta.3

**Comment by staaouat** [comment] 2020-03-24 17:54
The host failure problem is solved but the example still not working due the connection problem.

error: ClientException: Failed to connect to https://countries.trevorblades.com/

**Comment by staaouat** [comment] 2020-03-27 18:11
Can somebody point me to a worked example.

**Comment by staaouat** [comment] 2020-04-01 15:38
Finally figured out that it was because I had my VPN on.

**Comment by Aljabri-Salman** [comment] 2020-05-12 08:01
Same issue . Could you show how to install the beta package?

**Comment by kn4rfy** [comment] 2020-06-05 09:46
Adding this in my android manifest file solves my problem. I haven't checked with iOS yet

`<uses-permission android:name="android.permission.INTERNET" />`

**Comment by binaris-no** [comment] 2020-06-16 22:28
@Aljabri-Salman Probably too late as a tip for you but it might help others to know how to get onto the beta version/track given the severity of this issue (in the stable version).
https://pub.dev/packages/graphql/versions/3.1.0-beta.7#-installing-tab-
(Or https://pub.dev/packages/graphql_flutter/versions/3.1.0-beta.7#-installing-tab- if you use the full package.)

Otherwise I reproduce it simply by starting an app that makes an API call soon after, while the network is down. This is basically a simulation of a case where an app is started on mobile while for whatever reason their is no internet connection / the network is down.

**Comment by muhrahmatullah** [comment] 2020-07-01 13:55
also experiencing the same issue when testing using emulator but it works on real device, might be some connection problem

**Comment by micimize** [comment] 2020-07-01 15:18
@muhrahmatullah take a look at #212

**Comment by muhrahmatullah** [comment] 2020-07-03 12:39
@micimize checked the issue but the sample I am trying to use is the github_bloc one. I think it doesn't have a correlation with setting the local host (?)

**Comment by micimize** [comment] 2020-07-04 03:13
@muhrahmatullah I just mean that if your real device is trying to connect to localhost or `10.0.2.2` it won't be able to, regardless of everything else. Might not be the actual issue you're having though

**Comment by andersonmendesdev** [comment] 2020-07-21 12:24
I'm using the `graphql: ^3.0.2` version and I also have this problem, I really need to catch this exception for offline internet. Any suggestion?

**Comment by muhrahmatullah** [comment] 2020-07-23 11:34
@andersonmendesdev try use the beta version: graphql_flutter: ^3.1.0-beta.7

**Comment by andersonmendesdev** [comment] 2020-07-23 11:41
> @andersonmendesdev try use the beta version: graphql_flutter: ^3.1.0-beta.7

Yes, thank you, I'm already using it.

**Comment by andersonmendesdev** [comment] 2020-07-23 11:41
@muhrahmatullah  Yes, thank you, I'm already using it.

**Comment by speller** [comment] 2020-08-05 22:27
For those who are subscribed to this thread and don't know yet - version 3.1.0 has been released with the fix of this issue.

**Comment by micimize** [comment] 2020-08-06 00:52
closing for now – if anyone has a similar issue please comment or open a new one

**Closed by micimize** 2020-08-06 00:52 UTC

**Comment by diegothucao** [comment] 2020-08-06 01:20
Thanks so much for your fixing
