### ISSUE TITLE
Starwars example of subscription

### ISSUE THREAD

**Issue by chenxianqi** [zino-app/graphql-flutter#343] opened 2019-06-20 01:34 UTC
I can't run the example perfectly, I tried to execute and waited for the following error
![image](https://user-images.githubusercontent.com/27764334/59811922-8e875500-933e-11e9-833d-9fd7c1589713.png)
![image](https://user-images.githubusercontent.com/27764334/59811930-947d3600-933e-11e9-946a-3d2e7f3669a9.png)
![image](https://user-images.githubusercontent.com/27764334/59811939-9e069e00-933e-11e9-9902-05f48e2b31ca.png)

**Comment by chenxianqi** [comment] 2019-06-20 01:36
![image](https://user-images.githubusercontent.com/27764334/59811990-d0180000-933e-11e9-9d2f-2a491561fc09.png)

**Comment by micimize** [comment] 2019-06-22 17:43
This is an [introspection issue with angel-starwars-test-server](https://github.com/micimize/angel-starwars-test-server/issues/1) - tested and the actual subscription should still work fine:
```graphql
subscription {
  reviewAdded {
    stars, commentary, episode
  }
}
```

**Comment by micimize** [comment] 2019-06-27 14:14
closing as I failed to reproduce, and the issue is at least in part a `angel-starwars-test-server` issue. The issue might have been that you changed the host block, weren't running from a simulator, or had some other local connection issue like in #212 

```dart
String get host {
  if (Platform.isAndroid)
    return '10.0.2.2';
  else // for iOS simulator
    return 'localhost';
}
```

**Closed by micimize** 2019-06-27 14:14 UTC
Labels: docs & examples
